# Generated by Django 5.1.3 on 2026-02-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
