# Generated by Django 5.1.3 on 2026-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_predictionhistory_height_predictionhistory_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
